# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: ASSUME-DB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: ASSUME
  type: postgres
  url: assume_db:5432
  user: assume
  database: assume
  secureJsonData:
    password: assume
  jsonData:
    sslmode: "disable"
    postgresVersion: 1200
    timescaledb: true
  isDefault: true
  editable: true
